stages:
  - build
  - test-syntax
  - test-unit
  - test-coverage

build:
  stage: build
  script:
    - id -a
    - env PATH=$PATH:/opt/anaconda3/bin
    - echo "Insert build commands here here"

test-syntax:
  stage: test-syntax
  script:
    - pipeline_tests/lint_tests.sh

test-unit:
  stage: test-unit
  script:
    - pipeline_tests/unit_tests.sh

test-coverage:
  stage: test-coverage
  script:
    - pipeline_tests/cov_tests.sh
