image: python:3.8

before_script:
  - pipeline_tests/pretest_prep.sh

stages:
  - build
  - static-testing
  - unit-testing

build:
  stage: build
  script:
    - id -a
    - echo "Insert build commands here here"

test-syntax:
  stage: static-testing
  script:
    - pipeline_tests/lint_tests.sh
  artifacts:
    paths:
      - Vehicle-C++/Vehicle/Build/html
    expire_in: 7 days

test-unit:
  stage: unit-testing
  script:
    - pipeline_tests/unit_tests.sh
  artifacts:
    paths:
      - message-broker/broker/coverage
      - message-broker/testing-framework/coverage
    expire_in: 14 days

#test-coverage:
#  stage: unit-testing
#  script:
#    - pipeline_tests/cov_tests.sh
