---
- name: Install Git2.27
  hosts: all
  become: True
  become_user: root
  become_method: sudo
  ignore_errors: yes
  tasks:
    - name: Downloading Git2.27
      ansible.builtin.command: "wget -O /tmp/git27 https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.1.tar.gz -e use_proxy=yes -e https_proxy=contractorproxyeast.northgrum.com:80"
      args:
        warn: false
    - block:
        - name: Unzip Git2.27.tar
          ansible.builtin.command: "tar xvf git27"
          args:
            warn: false
            chdir: "/tmp"
        - name: Run Git make configure
          ansible.builtin.command: "make configure"
          args:
            warn: false
            chdir: "/tmp/git-2.27.1"
        - name: Run Git configure command
          ansible.builtin.command: "./configure --prefix=/usr"
          args:
            warn: false
            chdir: "/tmp/git-2.27.1"
        - name: Run Make command
          ansible.builtin.command: "make all doc info"
          args:
            warn: false
            chdir: "/tmp/git-2.27.1"
        - name: Install Git2.27
          ansible.builtin.command: "make install-doc install-html install-info"
          args:
            warn: false
            chdir: "/tmp/git-2.27.1"
        - name: Remove Files
          ansible.builtin.command: "rm -rf git-2.27.1"
          args:
            warn: false
            chdir: "/tmp"
