# install numpy, pendulum, requests, pytest, kombu
---
- name: Install necessary Python modules
  hosts: all
  become: true
  become_user: ansible

  tasks:
  - name: Install numpy
    pip:
      name: numpy
      state: --user
      executable: pip3.8
    environment:
      http_proxy: http://contractorproxyeast.northgrum.com:80
      https_proxy: https://contractorproxyeast.northgrum.com:80

  - name: Install pendulum
    pip:
      name: pendulum
      state: --user
      executable: pip3.8
    environment:
      http_proxy: http://contractorproxyeast.northgrum.com:80
      https_proxy: https://contractorproxyeast.northgrum.com:80

  - name: Install requests
    pip:
      name: requests
      state: --user
      executable: pip3.8
    environment:
      http_proxy: http://contractorproxyeast.northgrum.com:80
      https_proxy: https://contractorproxyeast.northgrum.com:80
  
  - name: Install pytest
    pip:
      name: pytest
      state: --user
      executable: pip3.8
    environment:
      http_proxy: http://contractorproxyeast.northgrum.com:80
      https_proxy: https://contractorproxyeast.northgrum.com:80

  - name: Install Kombu
    pip:
      name: kombu
      state: --user
      executable: pip3.8
    environment:
      http_proxy: http://contractorproxyeast.northgrum.com:80
      https_proxy: https://contractorproxyeast.northgrum.com:80